### ISSUE TITLE
constrmap

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterfaceSCS.jl#2]
I'm concerned about the use of `constrmap`. There is no guarantee in MOI that constraint references have unique indices across `(Function,Set)` pairs. The code makes an unstated assumption about an undocumented property of MOIU's implementation of standalone instance. Please avoid this, at the very least by documenting.

**Comment by blegat** [comment]
Yes, SDOI and ECOS are doing the same assumption. I agree that this should be documented better.
